README.md
chickenKyiv.js
groceristar.js
index.js
search.js
search.test.js

clean up and changed variables

---

index.test.js
projects/ChickenKyiv/chickenKyiv.js
projects/GroceriStar/groceristar.js
projects/MealCalendar/mealCalendar.js
projects/MealCalendar/mealCalendar.test.js
projects/Search/search.js
projects/Search/search.test.js

fixed data path

---

data/Ingredients/ingredients-old.json
data/Ingredients/ingredients.json
projects/GroceriStar/groceristar.test.js

I discovered the following while adding the new ingredients from [here](https://raw.githubusercontent.com/GroceriStar/static-data/master/dist/data/complex/Ingredients-500/Ingredients.js)
```
Old ingredients collection has a size of 1956 (distinct of 1887)
```
```
New ingredients collection has  a size 13308 (distinct of 13284)
```
After comparing using the distinct name keys from the old ingredient collection (`ie. size =1887`), we have a total of **13634**

Comparing and merging new ingredients

---

README.md

Cleaned code as needed by Task https://trello.com/c/E1FvUkv8/23-readme-clean-up .

clean Readme

---

index.js
projects/GroceriStar/groceristar.js

Result
```
[ { department_id: 1,
name: 'Fresh vegetables',
desc: 'desc for department1',
created_at: 1547668475013,
updated_at: 1547668475013 },
{ department_id: 2,
name: 'Condiments / sauces',
desc: 'desc for department1',
created_at: 1547668475013,
updated_at: 1547668475013 },
{ department_id: 3,
name: 'Dairy',
desc: 'desc for department1',
created_at: 1547668475013,
updated_at: 1547668475013 },
{ department_id: 4,
name: 'Cheese',
desc: 'desc for department1',
created_at: 1547668475013,
updated_at: 1547668475013 },
....
]
```

add getDepartmentsGraphQL

---

index.js
projects/GroceriStar/groceristar.js

In grocery.json we haven't fields id_1, and favs. I made like this
```
id_1: 1,
favs: false
```
I think id_1 it should be key of value in another column (one-to-one or many-to-many)
favs I don't know what is it I inserted false

add getGroceryGraphQLKey

---

src/projects/ChickenKyiv/chickenKyiv.js

I also made the proposed change to the getFiveRandomIngredients() method.

Now using lodash method in getRandomRecipe()

---

src/helper.js
src/projects/ChickenKyiv/chickenKyiv.js

Only using it in the chickenKyiv project for getIngredients3.

Added a __get() method to helper.js

---

src/helper.js
src/projects/ChickenKyiv/chickenKyiv.js

Moved chickenKyiv methods to helper.js, passes test, doesn't crash

Moved chickenKyiv methods to helper.js

---

src/helper.js
src/projects/ChickenKyiv/chickenKyiv.js
src/projects/ChickenKyiv/files.test.js
src/projects/GraphQL/files.test.js
src/projects/GraphQL/graphQL.js
src/projects/GroceriStar/groceristar.js
src/projects/GroceriStar/test/files.test.js
src/projects/MealCalendar/files.test.js
src/projects/MealCalendar/mealCalendar.js
src/projects/Search/files.test.js
src/projects/Search/search.js

1- Moved the __find() method to helper.js
2- All the file tests now use only the __find() method.

 Export raw files from each project

---

src/projects/GS-Loopback/loopback.js
src/projects/GS-Loopback/test/loopback.test.js

Implemented https://github.com/GroceriStar/groceristar-fetch/issues/211

Resolves "users" big object #211

---

src/helper.js

Fixes issue in helper.js, which makes tests pass again https://github.com/GroceriStar/groceristar-fetch/issues/318

fixed syntax error in helper.js

---

src/helper.js
src/projects/GraphQL/graphQL.js
src/projects/Search/search.js

Added helper methods `__generateId()` and `__generateDate()` in helper.js and cleaned up code using these new methods in graphQL.js https://github.com/GroceriStar/groceristar-fetch/issues/313

Updated helper.js and clean up code in graphQL.js

---

src/projects/ChickenKyiv/chickenKyiv.js
src/projects/Search/search.js

Completed some todo's

---

src/projects/GS-Loopback/loopback.js
src/projects/GroceriStar/groceristar.js

completed todos

---

src/projects/Showcase/showcase.js

Updated showcase.js

---

src/projects/GS-Loopback/loopback.js

Replaced hekper.js with utils.js

Updated loopback.js

---

src/projects/GroceriStar/play.js

Updated play.js

---

src/projects/GroceriStar/groceristar.js

Updated groceristar.js

---

src/projects/GraphQL/graphQL.js

replaced helper.js to utils.js

Updated graphQL.js

---

src/projects/MealCalendar/mealCalendar.js

Updated MealCalendar.js

---

src/projects/Search/play.js

Updated search/play.js

---

src/projects/Search/search.js

Updated search.js

---

src/utils.js

used lodash method to generate ID

Updated utils.js

---

src/projects/UnitConvertion/files.js

Objects(measurementunits and measurementSystems) are imported from sd-wrapper and exported

Updated files.js

---

src/projects/UnitConvertion/files.test.js

Tests are added to check objects are not empty

updated UnitConversion/files.test.js

---

src/projects/UnitConvertion/files.js

Updated with generatedMeasurementUnits and System

---

src/projects/UnitConvertion/files.test.js

it to test
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

updated files.test.js with a small change

---

src/projects/UnitConvertion/play.js

Created and updated play.js

---

package.json

Updated package.json with unitConversion/play.js

---

src/projects/Showcase/test/showcase.test.js

Reverts GroceriStar/groceristar-fetch#382

Revert "Update showcase.test.js"

---

src/projects/UnitConvertion/files.js

added some files

---

src/projects/UnitConvertion/files.test.js

adding some tests

---

src/projects/GroceriStar/test/getkeyArrayDepAnDing.test.js

Created tests for getkeyArrayDepAnDing method

---

src/projects/UnitConvertion/files.js
src/projects/UnitConvertion/test/files.test.js

renaming variables at UnitConvertion/test

---

Contributing.md

This PR is to add Contributing guidelines and development setup. Issue #437

[RP] Initial Contributing version

---

docs/grocery.js

generated grocery.js

---

docs/allergy.js

generated allergy.js

---

docs/ingredients.js

generated ingredients.js

---

package.json
src/projects/Showcase/play.js

start fixing showcase

---

debug/debugShowcase.js
package.json
src/projects/Showcase/showcase.js

fix & publish
